### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by lrrrfff** [zhaochenyang20/TOFEL_words_reviewer#11]
https://git.tsinghua.edu.cn/lurf21/words_reviewer

**Comment by zhaochenyang20** [comment]
写的不错，GUI 很实在，可以试试[优化 UI](https://blog.csdn.net/Nexfia/article/details/121011494)

**Comment by zhaochenyang20** [comment]
码风也不错，如果是初学，实在是很棒了！
