### ISSUE TITLE
HW

### ISSUE THREAD

**Issue by Lethe10137** [zhaochenyang20/TOFEL_words_reviewer#16]
https://github.com/Lethe10137/word-reviewer/
2021010826
一定程度上参考了https://github.com/zhaochenyang20/TOFEL_words_reviewer/

**Comment by zhaochenyang20** [comment]
功能全面，然而文件树复杂，建议在 readme 中解释自己的文件意义

**Comment by zhaochenyang20** [comment]
主文件尽量少命名为 `test.py`，且尽量别中英文混合注释

**Comment by zhaochenyang20** [comment]
你的函数模块适合包装在 utils.py 里面，而不是每个函数一个脚本文件

**Comment by zhaochenyang20** [comment]
文件冗杂，readme.md readme.MD
