### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by Sweetlemon68** [zhaochenyang20/TOFEL_words_reviewer#19]
[SAST2022-THWords](https://git.tsinghua.edu.cn/mrj21/sast2022-thwords)

A Python script generating word book, for SAST2022 Python track.

**Comment by zhaochenyang20** [comment]
表项良好，下次建议 html header 这些东西存在另一个文件里，然后读入，不必显示写出，影响代码阅读体验

**Comment by zhaochenyang20** [comment]
开源质量可嘉！
