### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by whimmmmm** [zhaochenyang20/TOFEL_words_reviewer#21]
https://git.tsinghua.edu.cn/luoyq21/python_hw1

**Comment by zhaochenyang20** [comment]
注意：

> 科学上网开启代理模式，并在命令行参数中输入代理信息

此处最好具体给出你的配置方式

**Comment by zhaochenyang20** [comment]
注释掉的代码较多，注意在你的 master 分支上尽量不要如此注释，这份代码适合放在 dev 上，而非 master

**Comment by zhaochenyang20** [comment]
代码风格需要改善，至少函数间需要空行

**Comment by zhaochenyang20** [comment]
没有写文档字符串，不便于他人阅读
