### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by xinghb21** [zhaochenyang20/TOFEL_words_reviewer#22]
https://git.tsinghua.edu.cn/xinghb21/sast2022-words_reviewer.git

**Comment by zhaochenyang20** [comment]
readme 的渲染有些问题，自行检查下

**Comment by zhaochenyang20** [comment]
尽量不要使用 input 方法，解析命令行更为常用

**Comment by zhaochenyang20** [comment]
Python 的 global 声明是很危险的，尽量少使用

**Comment by zhaochenyang20** [comment]
整体码风清奇，但是函数希望能够更加解耦
