### ISSUE TITLE
words-translation

### ISSUE THREAD

**Issue by zhuchuzhao** [zhaochenyang20/TOFEL_words_reviewer#25]
https://git.tsinghua.edu.cn/zhucz21/words-translation

**Comment by zhaochenyang20** [comment]
不宜将生成结果与工程代码放在同一个文件夹下，显得路径混乱

**Comment by zhaochenyang20** [comment]
`parser.add_argument('--random_rank','-r',help='Whether rank randomly or not, default not',type=bool,default=False)`
我没猜错的话，你 `-r False` 试试看，你能够测试出，此处是有 bug 的。
实际上 argparse 处理 bool 是很失败的，你需要了解 `store_true` 的用法，参考我的源代码

**Comment by zhaochenyang20** [comment]
至少说明，你的测试似乎不是很完全，建议多测试你的代码

**Comment by zhaochenyang20** [comment]
`def trans(string):`
此处你想表达用一个 string 作为参数传入函数，然而这么写不很合适。合适的写法是：`word: str`

**Comment by zhaochenyang20** [comment]
用了有道翻译的 API，不错！

**Comment by zhaochenyang20** [comment]
代码风格有所欠缺，注意我在群内发送的链接，有问题可以继续提问
