### ISSUE TITLE
sast2022_words_translator

### ISSUE THREAD

**Issue by Axian12138** [zhaochenyang20/TOFEL_words_reviewer#27]
https://github.com/Axian12138/sast2022_words_translator

**Comment by zhaochenyang20** [comment]
```
Returns:
        _type_: _description_
```
这一串你应该修改走

**Comment by zhaochenyang20** [comment]
整体代码风格合适，但是缺乏文档字符串，作为初学者值得表扬

**Comment by zhaochenyang20** [comment]
你可以思考下自己构建了这个 ndarray：
`words = np.asarray(list(filter(None, open(in_filename,'r').read().split("\n"))))`
而不用 list，有什么好处，有什么坏处。自己可以简单做实验试试看是否会有效率区别，以及思考为什么有这个效率区别。如果你没思考出来，欢迎周六来听我的进一步课程。
