### ISSUE TITLE
Hw1

### ISSUE THREAD

**Issue by HaoLi555** [zhaochenyang20/TOFEL_words_reviewer#29]
https://git.tsinghua.edu.cn/hao-li21/word-books

**Comment by zhaochenyang20** [comment]
使用了 `with open` 语法后不用显式地 close

**Comment by zhaochenyang20** [comment]
代码风格上，注意多加空格，代码看着太过密集

**Comment by zhaochenyang20** [comment]
缺乏文本字符串和必要的注释，``def convert(char):`` 这个函数命名很不合适。第一，Python 没有 char 类型，第二，你这里只表达了类型，没有表达物理意义

**Comment by zhaochenyang20** [comment]
我不知道你的 `argparser` 能不能这么使用，也即用 `while 1` 来读取，直到出现正确输入。然而这么输入实际上不太合适，很少有这么用的

**Comment by zhaochenyang20** [comment]
整体完成度很棒，`tqdm` 的运用非常优雅！
