### ISSUE TITLE
Homework1

### ISSUE THREAD

**Issue by Qinyu-Xu** [zhaochenyang20/TOFEL_words_reviewer#30]
https://git.tsinghua.edu.cn/xqy21/sast2022homework1

**Comment by zhaochenyang20** [comment]
```
    parser.add_argument(
        "-disable_random",
        action="store_false",
        dest="is_random",
        help="if you want to choose words in a sorted way, then use this",
    )
```
这个 `argparse` 显得冗长了些，最好用  `--d` 表示

**Comment by zhaochenyang20** [comment]
`words_lists = [[words[num*i+j] for j in range(num)] for i in range(len(words)//num)]`
这里写的不太 pythonic，可以查找下 Python 解包压包优化下码风。你这个推导显得不太自然流畅

**Comment by zhaochenyang20** [comment]
整体完成程度不错，关于列表解包和压包，自行知乎，然后关于推导的风格，我记得这本书的开头有讲过，你可以研究下:
https://zhaochenyang20.github.io/pdf/clean%20python.pdf
