### ISSUE TITLE
hw1

### ISSUE THREAD

**Issue by destiny718** [zhaochenyang20/TOFEL_words_reviewer#31]
[https://github.com/destiny718/TOFEL_translation](url)

**Comment by zhaochenyang20** [comment]
```
    Returns:
        _type_: _description_
```
这一串，你至少该把他删了，或者补齐

**Comment by zhaochenyang20** [comment]
```
        words = [line.strip() for line in f]
        while '' in words:
            words.remove('')
```
建议学习 `list` 的 `filter` 方法处理 `‘’` 的输入，而不是用这种 `remove` 方法

**Comment by zhaochenyang20** [comment]
你这里使用了 `sys` 库的 `sys.exit()`，如果你有兴趣，可以去研究下 `sys` 库和 `os` 库的区别，还有 `sys.exit()` 和 `exit()` 的区别

**Comment by zhaochenyang20** [comment]
`words = words[start-1:start+num-1]`
这里记得运算符左右加空格

**Comment by zhaochenyang20** [comment]
整体完成度很棒！代码风格整体不错！提出表扬！！
