### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by endazhao** [zhaochenyang20/TOFEL_words_reviewer#34]
https://git.tsinghua.edu.cn/zed21/wordbook

**Comment by zhaochenyang20** [comment]
![](https://user-images.githubusercontent.com/74843776/179352366-6083edc4-1c35-45ac-8b0d-1493b7ee03ce.png)
参考这一页面的说明，请尽量少使用特别大的 `try except` 模块来封装你的函数。大型 `try except` 模块只是用于你 debug 的，真正的工程代码，请仅仅把你明确知道会有 error 的代码块封装起来。

**Comment by zhaochenyang20** [comment]
没有定义主函数，且 `argpaser` 也没有封装，代码鲁邦性稍低。

**Comment by zhaochenyang20** [comment]
开源质量可嘉，作为初学者，非常优秀！

**Comment by zhaochenyang20** [comment]
![](https://user-images.githubusercontent.com/74843776/179352366-6083edc4-1c35-45ac-8b0d-1493b7ee03ce.png)
参考这一页面的说明，请尽量少使用特别大的 `try except` 模块来封装你的函数。大型 `try except` 模块只是用于你 debug 的，真正的工程代码，请仅仅把你明确知道会有 error 的代码块封装起来。

**Comment by zhaochenyang20** [comment]
没有定义主函数，且 `argpaser` 也没有封装，代码鲁邦性稍低。

**Comment by zhaochenyang20** [comment]
开源质量可嘉，作为初学者，非常优秀！
