### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by IridescentPig** [zhaochenyang20/TOFEL_words_reviewer#35]
https://github.com/IridescentPig/Wordbooks_generator

**Comment by zhaochenyang20** [comment]
![](https://user-images.githubusercontent.com/74843776/179352366-6083edc4-1c35-45ac-8b0d-1493b7ee03ce.png)
参考这一页面的说明，请尽量少使用特别大的 `try except` 模块来封装你的函数。大型 `try except` 模块只是用于你 debug 的，真正的工程代码，请仅仅把你明确知道会有 error 的代码块封装起来。

**Comment by zhaochenyang20** [comment]
没有定义主函数，且 `argpaser` 也没有封装，代码鲁邦性稍低。

**Comment by zhaochenyang20** [comment]
开源质量几乎是最好的，提及了对于生词本的格式要求，提出表扬，作为初学者，非常优秀！

**Comment by zhaochenyang20** [comment]
美中不足的是，你要求的生词本格式和用户理想的输入似乎差别太大，比如用户想要翻译词组，tide sb over，而按照你的程序，会分开翻译，这其实是不合理的。一般而言，我们是尽量希望用户输入合理，但是我们不能强求他们的输入，反而是我们要处理错误的输入~

**Comment by zhaochenyang20** [comment]
`from pathlib import *` 这个用法不太合适，尽量引入你使用的函数，而不是完全引入，污染命名空间。

**Comment by zhaochenyang20** [comment]
整体代码风格很简洁，注意空行会体验好些！作为初学者，表现可嘉！
