### ISSUE TITLE
homework submission

### ISSUE THREAD

**Issue by zhangziying56** [zhaochenyang20/TOFEL_words_reviewer#36]
https://github.com/ZZY32/Homework_creatingWordsBook
姓名见项目内README文件

**Comment by zhaochenyang20** [comment]
功能完整，但是代码鲁棒性几乎为 0，没有定义任何函数，导致其他模块完全没法调用 `main.py` 的函数

**Comment by zhaochenyang20** [comment]
整体上还是类似 `C` 的码风，老实说，作为初学者，这种习惯需要立刻改正。请你参考优秀作业完成函数封装

**Comment by zhaochenyang20** [comment]
https://github.com/zhaochenyang20/TOFEL_words_reviewer/issues/24
