### ISSUE TITLE
作业提交

### ISSUE THREAD

**Issue by cyh2004** [zhaochenyang20/TOFEL_words_reviewer#39]
https://git.tsinghua.edu.cn/chenying21/word-book-generator-and-translator/-/tree/master/
在readme里有身份信息

**Comment by KujoStar** [comment]
使用了爬虫技巧来实现翻译功能，第二节课的知识也得到了练习，看上去蛮好，比我这样偷懒用pygtrans的人好（划掉）

**Comment by KujoStar** [comment]
代码风格上，运算符左右加上空格会更好些

**Comment by KujoStar** [comment]
建议加上主函数提高一点代码的鲁棒性

**Comment by KujoStar** [comment]
很简洁的README.md（雾
