### ISSUE TITLE
HW Submission

### ISSUE THREAD

**Issue by YYadorigi** [zhaochenyang20/TOFEL_words_reviewer#40]
https://github.com/YYadorigi/Flat-Words-Slicer.git
2021012680

**Comment by KujoStar** [comment]
README.md写的非常优雅，令人称赞，格式清晰，功能介绍简洁明了，还贴心知道了如何安装虚拟环境并附上了requirements.yaml。

**Comment by KujoStar** [comment]
整体码风良好，条理清晰，注释详尽，值得称赞，本人向您学习

**Comment by KujoStar** [comment]
设置代理可以说做的很细心了（

**Comment by YYadorigi** [comment]
草，您怎么来批改了（

**Comment by zhaochenyang20** [comment]
我找的批改同学够专业吧（
