### ISSUE TITLE
hw1

### ISSUE THREAD

**Issue by foreverpiano** [zhaochenyang20/TOFEL_words_reviewer#41]
https://git.tsinghua.edu.cn/dhl21/summer-hw1

**Comment by KujoStar** [comment]
整体代码风格较好，值得本人学习

**Comment by KujoStar** [comment]
可以在代码中适当增加注释，便于读者理解

**Comment by KujoStar** [comment]
在定义函数的时候加入了提供类型注解的模块，可以进行类型检查和方便使用者使用自己的代码，挺好（？
