### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by xxxx-naive** [zhaochenyang20/TOFEL_words_reviewer#42]
https://github.com/Xu-Ivan/summer_homework_1
2021010748

**Comment by zhaochenyang20** [comment]
我严重怀疑你的 bug 是因为使用了不匹配的 Python 版本

**Comment by zhaochenyang20** [comment]
解决不了问题建议及时在群里提问，不要提交一个解决不了的 readme

**Comment by zhaochenyang20** [comment]
整体代码风格不错！！
